org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28


# Mod Info
mod_id=noxerna
mod_name=The Noxerna
mod_license=MIT
mod_version=25w16a
mod_group_id=net.chairmanfed.noxerna
mod_authors=ChairmanFed15
mod_description=Introducing Noxerna... A planet lurking in the far side of the universe. \nAdds a whole new dimension to the game

# Minecraft
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)

# NeoForge
neo_version=21.0.167
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

# Deps
jei_version=19.8.2.99
jade_version=5639932
better_advancements_version=5511371