org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17


# Mod Info
mod_id=noxerna
mod_name=The Noxerna
mod_license=MIT
mod_version=25w40a
mod_group_id=net.chairmanfed.noxerna
mod_authors=ChairmanFed15
mod_description=Introducing Noxerna... A planet lurking in the far side of the universe. \nAdds a whole new dimension to the game

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)

# NeoForge
neo_version=21.1.47
neo_version_range=[21.1.47,)
loader_version_range=[4,)

# Deps
jei_version=19.21.0.247
jade_version=6291517
better_advancements_version=5850587